package scaffold

import (
	"fmt"
	"os"
	"path/filepath"

	"gen-code/internal/matrix"
)

const signatureHeader = `// Code generated by Gen Code; DO NOT EDIT.
// Built with passion and code mastery.
`

func Scaffold(appName string, lang matrix.Language, fw matrix.Framework, pt matrix.ProjectType, c matrix.Complexity, outputDir string) error {
	m := matrix.GetMatrix(lang, fw, pt, c)

	signature := "// Code generated by Gen Code; DO NOT EDIT.\n// Created by: Moeed ul Hassan\n// Project: " + appName + "\n\n"

	for _, file := range m.Files {
		fullPath := filepath.Join(outputDir, file.Path)

		// Create directory if it doesn't exist
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("failed to create directory for %s: %w", file.Path, err)
		}

		// Prepare content with signature header
		content := signature + file.Content

		// Write file
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write file %s: %w", file.Path, err)
		}
	}

	return nil
}
